# Site settings
title: Adrian Rodriguez - Aspiring Cybersecurity Professional
description: Personal GitHub page showcasing projects, certifications, and resources related to cybersecurity.
baseurl: "/hacked-jekyll" # the subpath of your site, e.g. /blog
url: "https://your-github-username.github.io" # your GitHub Pages URL
author: Adrian Rodriguez

# Theme settings
theme: hacked-jekyll

# Exclude files
exclude:
  - LICENSE
  - README.md
  - vendor/

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Sass configuration
sass:
  sourcemap: never

# Appearance customizations (optional for theme styling)
color_bg: gray-9 # Background color
color_punct: green-9 # Punctuation color (quotes, commas, brackets)
color_key: green-4 # Key color
color_value: green-4 # Value color
color_hover: green-5 # Hover color for links
quotes: true # Enable quotes around key-value pairs
commas: true # Enable commas between key-value pairs
lowercase: true # Make all keys and values lowercase
newtab: false # Open links in the same tab

# Social Links (customize with your own links)
social_links:
  - name: GitHub
    url: https://github.com/your-github-username
  - name: LinkedIn
    url: https://www.linkedin.com/in/your-linkedin-username

